#!/bin/sh

CWD="$(git rev-parse --show-toplevel)"
BIN_PATH="$CWD/node_modules/.bin"

# STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.jsx\?$')

cd $CWD

test() {
  JEST="$BIN_PATH/jest"

  # Check for jest
  if [[ ! -x "$JEST" ]]; then
    printf "\t\033[41mPlease install Jest\033[0m\n"
    exit 1
  fi

  printf "\nRunning all tests\n"

  $JEST --bail --passWithNoTests

  if [[ $? == 0 ]]; then
    printf "\n\033[1;32mTests Passed\033[0m\n"
  else
    printf "\n\033[41mTest Failed:\033[0m Fix test errors and try again!\n"
    exit 1
  fi
}

test

exit 0
